SDC-15926. stage.test_elasticsearch_stages.test_index_and_template_with_plus_get_encoded is failing
All the test fail with the error message

TimeoutError: Timed out after 30 seconds while waiting for status FINISHED.

Increasing the timeout to see if this is the root cause of the issue.
If not, another issue will be created.

Change-Id: I87de6591945732b42823341572b45d80dca549e3
Reviewed-on: https://review.streamsets.dev/c/datacollector-tests/+/2623
Reviewed-by: Santhosh Kumar Manavasi Lakshminarayanan <santhosh@streamsets.com>